import Radio from "./Radio";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Radio,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=6009%3A2633",
  {
    imports: ["import { Radio } from '@bcgov/design-system-react-components'"],
    props: {
      // These props were automatically mapped based on your linked code:
      children: figma.string("Label"),
      isDisabled: figma.enum("State", {
        Disabled: true,
      }),
      // No matching props could be found for these Figma properties:
      // "active": figma.boolean('Active')
    },
    example: (props) => (
      <Radio value={props.children} isDisabled={props.isDisabled}>
        {props.children}
      </Radio>
    ),
  }
);
