import React from "react"
import Radio from "./Radio"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Radio,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=6009%3A2633",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "label": figma.boolean('Label'),
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Hover": "hover",
      //   "Touch": "touch",
      //   "Focus": "focus",
      //   "Disabled": "disabled",
      //   "Error": "error"
      // }),
      // "active": figma.boolean('Active')
    },
    example: (props) => <Radio value={/* TODO */} />,
  },
)
