import CheckboxGroup from "./CheckboxGroup";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  CheckboxGroup,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=6009%3A993",
  {
    imports: [
      "import { CheckboxGroup, Checkbox } from '@bcgov/design-system-react-components'",
    ],
    props: {
      // These props were automatically mapped based on your linked code:
      orientation: figma.enum("Orientation", {
        Horizontal: "horizontal",
        Vertical: "vertical",
      }),
      label: figma.textContent("Label"),
      description: figma.textContent("Description"),
      children: figma.slot("Default"),
      isInvalid: figma.boolean("Error text"),
      errorMessage: figma.textContent("Error message"),
    },
    example: (props) => (
      <CheckboxGroup
        orientation={props.orientation}
        isInvalid={props.isInvalid}
        errorMessage={props.errorMessage}
      >
        {props.children}
      </CheckboxGroup>
    ),
  }
);
