import React from "react"
import CheckboxGroup from "./CheckboxGroup"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  CheckboxGroup,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=6009%3A993",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "label": figma.boolean('Label'),
      // "description": figma.boolean('Description'),
      // "errorText": figma.boolean('Error text'),
      // "count": figma.enum('Count', {
      //   "2": "2",
      //   "3": "3",
      //   "4": "4",
      //   "5": "5",
      //   "6": "6",
      //   "7": "7",
      //   "8": "8"
      // }),
      // "layout": figma.enum('Layout', {
      //   "Vertical": "vertical",
      //   "Horizontal": "horizontal"
      // })
    },
    example: (props) => <CheckboxGroup />,
  },
)
