import InlineAlert from "./InlineAlert";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  InlineAlert,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=5347%3A1946",
  {
    imports: [
      "import { InlineAlert } from '@bcgov/design-system-react-components'",
    ],
    props: {
      variant: figma.enum("Type", {
        Info: "info",
        Warning: "warning",
        Success: "success",
        Error: "danger",
      }),
      title: figma.textContent("Alert title"),
      description: figma.string("Description text"),
      isCloseable: figma.boolean("Close"),
      isIconHidden: figma.boolean("Icon", { true: false, false: true }),
      // No matching props could be found for these Figma properties:
      // "actions": figma.boolean('Actions'),
    },
    example: (props) => (
      <InlineAlert
        variant={props.variant}
        title={props.title}
        description={props.description}
        isCloseable={props.isCloseable}
        isIconHidden={props.isIconHidden}
      />
    ),
  }
);
