import React from "react"
import InlineAlert from "./InlineAlert"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  InlineAlert,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=5347%3A1946",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      description: figma.string("Description text"),
      // No matching props could be found for these Figma properties:
      // "description": figma.boolean('Description'),
      // "icon": figma.boolean('Icon'),
      // "close": figma.boolean('Close'),
      // "actions": figma.boolean('Actions'),
      // "descriptionText": figma.string('Description text'),
      // "type": figma.enum('Type', {
      //   "Info": "info",
      //   "Warning": "warning",
      //   "Success": "success",
      //   "Error": "error"
      // })
    },
    example: (props) => <InlineAlert description={props.description} />,
  },
)
