# Dependabot config
# Docs: https://docs.github.com/en/code-security/reference/supply-chain-security/dependabot-options-reference

version: 2
updates:
  # Dependency updates for @bcgov/design-tokens and @bcgov/design-system-react-components
  - package-ecosystem: "npm"
    directories: ["/packages/react-components", "/packages/design-tokens"]
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"
    # Wait 7 days before opening PRs for new versions
    cooldown:
      default-days: 7
      include: ["*"]
    open-pull-requests-limit: 10
    # Do not open PRs for major version updates
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    # Group related dependency updates
    groups:
      storybook:
        applies-to: version-updates
        patterns: ["storybook", "@storybook/*", "eslint-plugin-storybook"]
      vitest:
        applies-to: version-updates
        patterns: ["vitest", "@vitest/*"]
      rollup:
        applies-to: version-updates
        patterns: ["rollup", "@rollup/*"]
      typescript-eslint:
        applies-to: version-updates
        patterns: ["typescript-eslint", "@typescript-eslint/*"]

  # Dependency updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"
    # Wait 7 days before opening PRs for new versions
    cooldown:
      default-days: 7
      include: ["*"]
    open-pull-requests-limit: 10
    groups:
      github-actions:
        applies-to: version-updates
        patterns: ["actions/*"]
