import React from "react"
import Accordion from "./Accordion"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Accordion,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=7780%3A1928",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      label: figma.string("Text"),
      isDisabled: figma.enum("State", {
        Disabled: true,
      }),
      // No matching props could be found for these Figma properties:
      // "text": figma.string('Text'),
      // "opened": figma.boolean('Opened')
    },
    example: (props) => (
      <Accordion label={props.label} isDisabled={props.isDisabled} />
    ),
  },
)
