import Select from "./Select";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Select,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=3572%3A4229",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("Size", {
        Small: "small",
        Medium: "medium",
      }),
      label: figma.nestedProps("Label", figma.string("Label text")),
      description: figma.textContent("Description text"),
      isOpen: figma.boolean("Menu opened"),
      isRequired: figma.nestedProps("Label", figma.boolean("Required")),
      isDisabled: figma.enum("State", {
        Disabled: true,
      }),
    },
    example: (props) => (
      <Select
        size={props.size}
        label={props.label}
        description={props.description}
        isOpen={props.isOpen}
        isRequired={props.isRequired}
        isDisabled={props.isDisabled}
      />
    ),
  }
);
