import React from "react"
import AlertBanner from "./AlertBanner"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  AlertBanner,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=7782%3A3193",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      variant: figma.enum("Variant", {
        Info: "info",
        Success: "success",
        Warning: "warning",
        Danger: "danger",
        Black: "black",
      }),
      // No matching props could be found for these Figma properties:
      // "icon": figma.boolean('Icon'),
      // "close": figma.boolean('Close'),
      // "action": figma.boolean('Action')
    },
    example: (props) => <AlertBanner variant={props.variant} />,
  },
)
