import React from "react"
import AlertBanner from "./AlertBanner"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  AlertBanner,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=7782%3A3193",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "icon": figma.boolean('Icon'),
      // "close": figma.boolean('Close'),
      // "action": figma.boolean('Action'),
      // "type": figma.enum('Type', {
      //   "Info": "info",
      //   "Success": "success",
      //   "Warning": "warning",
      //   "Danger": "danger",
      //   "Black": "black"
      // })
    },
    example: (props) => <AlertBanner />,
  },
)
