import TagGroup from "./TagGroup";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  TagGroup,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=3970%3A2221",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      hidden: figma.boolean("Icon"),
      // No matching props could be found for these Figma properties:
      // "errorText": figma.boolean('Error text'),
      // "label": figma.boolean('Label'),
      // "closeable": figma.boolean('Closeable')
    },
    example: (props) => <TagGroup hidden={props.hidden} />,
  }
);
