import React from "react"
import TagGroup from "./TagGroup"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  TagGroup,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=3970%3A2221",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "errorText": figma.boolean('Error text'),
      // "label": figma.boolean('Label'),
      // "count": figma.enum('Count', {
      //   "2": "2",
      //   "4": "4",
      //   "3": "3",
      //   "5": "5",
      //   "6": "6",
      //   "7": "7",
      //   "8": "8"
      // }),
      // "closeable": figma.boolean('Closeable'),
      // "icon": figma.boolean('Icon')
    },
    example: (props) => <TagGroup />,
  },
)
