import TagGroup from "./TagGroup";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  TagGroup,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=3970%3A2221",
  {
    imports: [
      "import { TagGroup, TagList, Tag } from '@bcgov/design-system-react-components'",
    ],
    props: {
      label: figma.textContent("Label"),
      description: figma.textContent("Description"),
      errorMessage: figma.textContent("Error text"),
      children: figma.slot("Slot"),
      // No matching props could be found for these Figma properties:
      // "closeable": figma.boolean('Closeable')
    },
    example: (props) => (
      <TagGroup
        label={props.label}
        description={props.description}
        errorMessage={props.errorMessage}
      >
        {props.children}
      </TagGroup>
    ),
  }
);
