import TimeField from "./TimeField";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  TimeField,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=19285%3A4805",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("Size", {
        Medium: "medium",
        Small: "small",
      }),
      hideTimeZone: figma.boolean("Timezone", {
        false: true,
        true: false,
      }),
      hourCycle: figma.enum("Hour Cycle", {
        "12-hour": 12,
        "24-hour": 24,
      }),
      granularity: figma.enum("Granularity", {
        Hour: "hour",
        Minute: "minute",
        Second: "second",
      }),
      label: figma.nestedProps("Label", figma.string("Label text")),
      description: figma.textContent("Description"),
      isRequired: figma.nestedProps("Label", figma.boolean("Required")),
      isDisabled: figma.enum("State", {
        Disabled: true,
      }),
      errorMessage: figma.textContent("Error text"),
      // No matching props could be found for these Figma properties:
      // "showLabel": figma.boolean('Show label'),
    },
    example: (props) => (
      <TimeField
        size={props.size}
        label={props.label}
        description={props.description}
        granularity={props.granularity}
        hourCycle={props.hourCycle}
        hideTimeZone={props.hideTimeZone}
        isRequired={props.isRequired}
        isDisabled={props.isDisabled}
        errorMessage={props.errorMessage}
      />
    ),
  }
);
