import TimeField from "./TimeField";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  TimeField,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=19285%3A4805",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("Size", {
        Medium: "medium",
        Small: "small",
      }),
      hideTimeZone: figma.boolean("Timezone"),
      isDisabled: figma.enum("State", {
        Disabled: true,
      }),
      hidden: figma.enum("State", {
        Disabled: true,
      }),
      // No matching props could be found for these Figma properties:
      // "showLabel": figma.boolean('Show label'),
      // "description": figma.boolean('Description'),
      // "timezone": figma.boolean('Timezone')
    },
    example: (props) => (
      <TimeField
        size={props.size}
        hideTimeZone={props.hideTimeZone}
        isDisabled={props.isDisabled}
        hidden={props.hidden}
      />
    ),
  }
);
