import React from "react"
import TextArea from "./TextArea"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  TextArea,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=4157%3A2531",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      isDisabled: figma.enum("State", {
        Disabled: true,
      }),
      isRequired: figma.boolean("Filled"),
      // No matching props could be found for these Figma properties:
      // "showCount": figma.boolean('Show count'),
      // "description": figma.boolean('Description'),
      // "label": figma.boolean('Label'),
      // "scrollable": figma.boolean('Scrollable')
    },
    example: (props) => (
      <TextArea isDisabled={props.isDisabled} isRequired={props.isRequired} />
    ),
  },
)
