import React from "react"
import TextArea from "./TextArea"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  TextArea,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=4157%3A2531",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "scrollable": figma.boolean('Scrollable'),
      // "label": figma.boolean('Label'),
      // "description": figma.boolean('Description'),
      // "showCount": figma.boolean('Show count'),
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Hover": "hover",
      //   "Disabled": "disabled",
      //   "Focused": "focused",
      //   "Error": "error"
      // }),
      // "filled": figma.boolean('Filled')
    },
    example: (props) => <TextArea />,
  },
)
