import TextArea from "./TextArea";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  TextArea,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=4157%3A2531",
  {
    props: {
      label: figma.nestedProps("Label", figma.string("Label text")),
      description: figma.nestedProps(
        "Description",
        figma.textContent("Description")
      ),
      errorMessage: figma.textContent("Error text"),
      isRequired: figma.nestedProps("Label", figma.boolean("Required")),
      isDisabled: figma.enum("State", {
        Disabled: true,
      }),
      // No matching props could be found for these Figma properties:
      // "showCount": figma.boolean('Show count'),
      // "scrollable": figma.boolean('Scrollable')
    },
    example: (props) => (
      <TextArea
        label={props.label}
        description={props.description}
        isRequired={props.isRequired}
        isDisabled={props.isDisabled}
        errorMessage={props.errorMessage}
      />
    ),
  }
);
