import NumberField from "./NumberField";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  NumberField,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=14421%3A4311",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("Size", {
        Small: "small",
        Medium: "medium",
      }),
      label: figma.string("Label text"),
      description: figma.textContent("Description"),
      isRequired: figma.nestedProps("Label", figma.boolean("Required")),
      isDisabled: figma.enum("State", {
        Disabled: true,
      }),
      isReadOnly: figma.enum("State", {
        "Read only": true,
      }),
      hidden: figma.enum("State", {
        Disabled: true,
      }),
      // No matching props could be found for these Figma properties:
      // "units": figma.boolean('Units'),
      // "currency": figma.boolean('Currency'),
      // "decimal": figma.boolean('Decimal'),
      // "description": figma.boolean('Description'),
      // "label": figma.boolean('Label'),
      // "value": figma.boolean('Value')
    },
    example: (props) => (
      <NumberField
        size={props.size}
        hidden={props.hidden}
        label={props.label}
        description={props.description}
        isRequired={props.isRequired}
        isDisabled={props.isDisabled}
        isReadOnly={props.isReadOnly}
      />
    ),
  }
);
