import React from "react"
import SvgExclamationIcon from "./SvgExclamationIcon"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  SvgExclamationIcon,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=3351%3A1750",
  {
    props: {},
    example: (props) => <SvgExclamationIcon />,
  },
)
