import ProgressBar from "./ProgressBar";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  ProgressBar,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=16649%3A4759",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("Track Size", {
        Small: "small",
        Medium: "medium",
        Large: "large",
      }),
      isIndeterminate: figma.enum("Style", {
        Indeterminate: true,
      }),
      // No matching props could be found for these Figma properties:
      // "label": figma.string('Label'),
      // "value": figma.string('Value'),
      // "showLabelValue": figma.boolean('Show label & value'),
      // "orientation": figma.enum('Orientation', {
      //   "Horizontal": "horizontal",
      //   "Vertical": "vertical"
      // }),
      // "color": figma.enum('Color', {
      //   "Default": "default",
      //   "Over Background": "over-background"
      // })
    },
    example: (props) => (
      <ProgressBar size={props.size} isIndeterminate={props.isIndeterminate} />
    ),
  }
);
