import React from "react"
import Tag from "./Tag"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Tag,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=3426%3A4647",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      icon: figma.instance("Swap icon"),
      color: figma.enum("Color", {
        Blue: "blue",
        "Theme gold": "bc-gold",
        Dark: "dark",
        Gray: "grey",
        Green: "green",
        Red: "red",
        Yellow: "yellow",
      }),
      // No matching props could be found for these Figma properties:
      // "tagText": figma.string('Tag text'),
      // "closeable": figma.boolean('Closeable'),
      // "swapIcon": figma.instance('Swap icon'),
      // "icon": figma.boolean('Icon'),
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Selected": "selected",
      //   "Pressed/focused": "pressed-focused",
      //   "Disabled": "disabled"
      // })
    },
    example: (props) => <Tag icon={props.icon} color={props.color} />,
  },
)
