import Tag from "./Tag";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Tag,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=3426%3A4647",
  {
    imports: ["import { Tag } from '@bcgov/design-system-react-components'"],
    props: {
      // These props were automatically mapped based on your linked code:
      icon: figma.instance("Icon placeholder"),
      color: figma.enum("Color", {
        "Theme blue": "blue",
        "Theme gold": "bc-gold",
        Dark: "dark",
        Gray: "grey",
        Green: "green",
        Red: "red",
        Yellow: "yellow",
      }),
      tagStyle: figma.enum("Style", {
        Rectangular: "rectangular",
        Circular: "circular",
      }),
      size: figma.enum("Size", {
        Small: "small",
        Medium: "medium",
      }),
      children: figma.string("Tag text"),
      isDisabled: figma.enum("State", {
        Disabled: true,
      }),
      // No matching props could be found for these Figma properties:
      // "showIcon": figma.boolean('Show icon'),
      // "closeable": figma.boolean('Closeable'),
    },
    example: (props) => (
      <Tag
        icon={props.icon}
        color={props.color}
        tagStyle={props.tagStyle}
        size={props.size}
        isDisabled={props.isDisabled}
      >
        {props.children}
      </Tag>
    ),
  }
);
