name: Bug
description: Report an error or unexpected behaviour in a component
labels: ["bug"]
projects: ["bcgov/121"]
assignees:
  - mkernohanbc
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much information as possible, including screenshots if possible.
  - type: input
    id: component
    attributes:
      label: Component
      description: Which component does this bug affect?
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the error or unexpected behaviour you observed, and provide screenshots if possible
      placeholder: Tell us what's going wrong
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Describe the circumstances under which the bug occurs
      placeholder: What were you doing when the bug occurred?
    validations:
      required: true
  - type: textarea
    id: technical
    attributes:
      label: Technical information
      description: What browsers or platforms does the bug affect?
      placeholder: Desktop or mobile? All browsers, or only one?
    validations:
      required: true
