import React from "react"
import Switch from "./Switch"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Switch,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=5146%3A248",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      defaultSelected: figma.enum("State", {
        Default: true,
      }),
      isSelected: figma.boolean("Active"),
      isDisabled: figma.enum("State", {
        Disabled: true,
      }),
      // No matching props could be found for these Figma properties:
      // "label": figma.boolean('Label'),
      // "layout": figma.enum('Layout', {
      //   "No label": "no-label",
      //   "Label after": "label-after",
      //   "Label before": "label-before"
      // })
    },
    example: (props) => (
      <Switch
        defaultSelected={props.defaultSelected}
        isSelected={props.isSelected}
        isDisabled={props.isDisabled}
      />
    ),
  },
)
