import Switch from "./Switch";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Switch,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=5146%3A248",
  {
    props: {
      isSelected: figma.boolean("Active"),
      isDisabled: figma.enum("State", {
        Disabled: true,
      }),
      labelPosition: figma.enum("Layout", {
        "label-before": "left",
        "label-after": "right",
      }),
      children: figma.textContent("Label"),
    },
    example: (props) => (
      <Switch
        isSelected={props.isSelected}
        isDisabled={props.isDisabled}
        labelPosition={props.labelPosition}
      >
        {props.children}
      </Switch>
    ),
  }
);
