import AccordionGroup from "./AccordionGroup"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  AccordionGroup,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=7780%3A2135",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      title: figma.string("Text"),
      isDisabled: figma.enum("State", {
        Disabled: true,
      }),
      // No matching props could be found for these Figma properties:
      // "text": figma.string('Text'),
      // "numberOfAccordions": figma.enum('Number of accordions', {
      //   "2": "2",
      //   "3": "3",
      //   "4": "4",
      //   "5": "5",
      //   "6": "6",
      //   "7": "7",
      //   "8": "8"
      // })
    },
    example: (props) => (
      <AccordionGroup title={props.title} isDisabled={props.isDisabled} />
    ),
  },
)
