import AccordionGroup from "./AccordionGroup";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  AccordionGroup,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=7780%3A2135",
  {
    props: {
      title: figma.string("Accordion group label"),
      isDisabled: figma.enum("State", {
        Disabled: true,
      }),
      children: figma.slot("Default"),
    },
    example: (props) => (
      <AccordionGroup title={props.title} isDisabled={props.isDisabled}>
        {props.children}
      </AccordionGroup>
    ),
  }
);
