import React from "react"
import AccordionGroup from "./AccordionGroup"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  AccordionGroup,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=7780%3A2135",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      isDisabled: figma.enum("State", {
        Disabled: true,
      }),
      hidden: figma.enum("State", {
        Disabled: true,
      }),
      // No matching props could be found for these Figma properties:
      // "accordionGroupLabel": figma.string('Accordion group label'),
      // "title": figma.boolean('Title')
    },
    example: (props) => (
      <AccordionGroup isDisabled={props.isDisabled} hidden={props.hidden} />
    ),
  },
)
