import React from "react"
import Calendar from "./Calendar"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Calendar,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=15871%3A6832",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "visibleMonths": figma.enum('Visible months', {
      //   "1": "1",
      //   "2": "2",
      //   "3": "3"
      // })
    },
    example: (props) => <Calendar />,
  },
)
