#!/usr/bin/env node

import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { parseArgs } from "node:util";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/* CLI flags */
const { values } = parseArgs({
  args: process.argv.slice(2),
  options: {
    cwd: { type: "string" },
    check: { type: "boolean", default: false },
    force: { type: "boolean", default: false },
  },
  strict: true,
  allowPositionals: true,
});

/* Create agent files at root of user's repository */
function findGitRoot(startDir) {
  let dir = path.resolve(startDir);

  while (true) {
    if (fs.existsSync(path.join(dir, ".git"))) {
      return dir;
    }

    const parent = path.dirname(dir);
    if (parent === dir) {
      return null;
    }

    dir = parent;
  }
}

/* User can override file creation location with --cwd flag */
const cliCwd = values.cwd;
const repoRoot = path.resolve(
  cliCwd || findGitRoot(process.cwd()) || process.cwd()
);

const templateRoot = path.join(__dirname, "..", "templates", "agents");
const packageVersion = JSON.parse(
  fs.readFileSync(path.join(__dirname, "..", "package.json"), "utf8")
).version;

function readTemplate(fileName) {
  return fs.readFileSync(path.join(templateRoot, fileName), "utf8");
}

function hashContent(content) {
  return crypto.createHash("sha256").update(content).digest("hex");
}

/* Source content for generated files */
const instructionsContent = readTemplate("copilot-instructions.md");
const skillContentSetup = readTemplate("setup-design-system.skill.md");

const targets = [
  /* Create basic B.C. Design System instruction set in .github/instructions */
  {
    file: path.join(
      repoRoot,
      ".github",
      "instructions",
      "design-system.instructions.md"
    ),
    content: instructionsContent,
    label: "design system instructions",
  },
  /* Create B.C. Design System agent in .agents */
  {
    file: path.join(repoRoot, ".agents", "bc-design-system.agent.md"),
    content: `---\nname: bc-design-system\ndescription: Use the BC Gov design system for user interface work\n---\n\n${instructionsContent}`,
    label: "GitHub Copilot agent definition",
  },
  /* Create B.C. Design System setup/config skill in .agents/skills */
  {
    file: path.join(repoRoot, ".agents", "skills", "setup-design-system.md"),
    content: skillContentSetup,
    label: "agent skill",
  },
];

/*
 * Generated files are tracked in a manifest keyed by the recorded hash of
 * what we last wrote. That lets a re-run tell "user hasn't touched this
 * since we generated it" (safe to update) apart from "user edited this"
 * (do not clobber) without embedding markers in the generated content
 * itself, which would corrupt files that start with YAML frontmatter.
 */
const manifestFile = path.join(repoRoot, ".agents", "design-system.lock.json");

function readManifest() {
  if (!fs.existsSync(manifestFile)) {
    return { files: {} };
  }
  try {
    return JSON.parse(fs.readFileSync(manifestFile, "utf8"));
  } catch {
    return { files: {} };
  }
}

const manifest = readManifest();
const isCheck = values.check;
const isForce = values.force;

const counts = {
  created: 0,
  updated: 0,
  unchanged: 0,
  modified: 0,
  untracked: 0,
};

for (const target of targets) {
  const relPath = path.relative(repoRoot, target.file);
  const newHash = hashContent(target.content);
  const entry = manifest.files[relPath];
  const exists = fs.existsSync(target.file);

  function write(reason) {
    if (!isCheck) {
      fs.mkdirSync(path.dirname(target.file), { recursive: true });
      fs.writeFileSync(target.file, target.content, "utf8");
      manifest.files[relPath] = { packageVersion, hash: newHash };
    }
    console.log(`${reason} ${target.label}: ${relPath}`);
  }

  if (!exists) {
    write(isCheck ? "Would create" : "Created");
    counts.created += 1;
    continue;
  }

  const onDiskHash = hashContent(fs.readFileSync(target.file, "utf8"));

  if (!entry) {
    /* Predates version tracking, or was never generated by this tool */
    console.log(
      `Skipping untracked ${target.label} (not created by this tool): ${relPath}`
    );
    counts.untracked += 1;
    continue;
  }

  if (onDiskHash === newHash) {
    if (entry.hash !== newHash && !isCheck) {
      manifest.files[relPath] = { packageVersion, hash: newHash };
    }
    counts.unchanged += 1;
    continue;
  }

  if (onDiskHash === entry.hash) {
    /* Unmodified since last generation, so the new template is safe to apply */
    write(isCheck ? "Update available for" : "Updated");
    counts.updated += 1;
    continue;
  }

  /* On-disk content diverges from both the last-generated hash and the
   * current template, meaning the user edited it. */
  if (isForce) {
    if (!isCheck) {
      fs.copyFileSync(target.file, `${target.file}.bak`);
    }
    write(isCheck ? "Would overwrite modified" : "Overwrote modified");
    console.log(`  (previous version backed up to ${relPath}.bak)`);
    counts.modified += 1;
    continue;
  }

  if (!isCheck) {
    fs.writeFileSync(`${target.file}.new`, target.content, "utf8");
  }
  console.log(
    `Local edits detected in ${target.label}, leaving it alone: ${relPath}`
  );
  console.log(
    `  New version written to ${relPath}.new — merge manually, or re-run with --force to overwrite (backs up the old file first)`
  );
  counts.modified += 1;
}

if (!isCheck) {
  fs.mkdirSync(path.dirname(manifestFile), { recursive: true });
  fs.writeFileSync(manifestFile, JSON.stringify(manifest, null, 2) + "\n", "utf8");
}

console.log();
console.log(
  isCheck
    ? `Check complete: ${counts.created} to create, ${counts.updated} to update, ${counts.modified} with local edits, ${counts.unchanged} up to date, ${counts.untracked} untracked.`
    : `Done: ${counts.created} created, ${counts.updated} updated, ${counts.modified} with local edits left in place, ${counts.unchanged} already up to date, ${counts.untracked} untracked.`
);

if (counts.created > 0 || counts.updated > 0) {
  console.log(
    "GitHub Copilot will now see these instructions in the repository root workspace."
  );
}
