import TextField from "./TextField";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  TextField,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=3649%3A14334",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("Size", {
        Medium: "medium",
        Small: "small",
      }),
      label: figma.nestedProps("Label", figma.string("Label text")),
      description: figma.nestedProps(
        "Description",
        figma.textContent("Description text")
      ),
      errorMessage: figma.textContent("Error text"),
      iconLeft: figma.instance("Left icon placeholder"),
      iconRight: figma.instance("Right icon placeholder"),
      isRequired: figma.nestedProps("Label", figma.boolean("Required")),
      isDisabled: figma.enum("State", {
        Disabled: true,
      }),
      // No matching props could be found for these Figma properties:
      // "showLeftIcon": figma.boolean('Show left Icon'),
      // "showRightIcon": figma.boolean('Show right icon'),
      // "showLabel": figma.boolean('Show label'),
      // "prefix": figma.boolean('Prefix'),
      // "suffix": figma.boolean('Suffix')
    },
    example: (props) => (
      <TextField
        size={props.size}
        label={props.label}
        description={props.description}
        iconLeft={props.iconLeft}
        iconRight={props.iconRight}
        isRequired={props.isRequired}
        isDisabled={props.isDisabled}
        errorMessage={props.errorMessage}
      />
    ),
  }
);
