import React from "react"
import TextField from "./TextField"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  TextField,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=3649%3A14334",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("Size", {
        Medium: "medium",
        Small: "small",
      }),
      description: figma.string("Description text"),
      // No matching props could be found for these Figma properties:
      // "prefix": figma.boolean('Prefix'),
      // "description": figma.boolean('Description'),
      // "rightIconPlaceholder": figma.instance('Right icon placeholder'),
      // "descriptionText": figma.string('Description text'),
      // "leftIconPlaceholder": figma.instance('Left icon placeholder'),
      // "showLabel": figma.boolean('Show label'),
      // "showRightIcon": figma.boolean('Show right icon'),
      // "suffix": figma.boolean('Suffix'),
      // "showLeftIcon": figma.boolean('Show left Icon'),
      // "state": figma.enum('State', {
      //   "Placeholder": "placeholder",
      //   "Hover": "hover",
      //   "Filled": "filled",
      //   "Typing": "typing",
      //   "Disabled": "disabled",
      //   "Error": "error",
      //   "Focused": "focused"
      // })
    },
    example: (props) => (
      <TextField size={props.size} description={props.description} />
    ),
  },
)
