import React from "react"
import TextField from "./TextField"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  TextField,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=3649%3A14334",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("Size", {
        Medium: "medium",
        Small: "small",
      }),
      description: figma.string("Description text"),
      iconLeft: figma.instance("Left icon placeholder"),
      iconRight: figma.instance("Right icon placeholder"),
      isDisabled: figma.enum("State", {
        Disabled: true,
      }),
      // No matching props could be found for these Figma properties:
      // "showLeftIcon": figma.boolean('Show left Icon'),
      // "showRightIcon": figma.boolean('Show right icon'),
      // "showLabel": figma.boolean('Show label'),
      // "leftIconPlaceholder": figma.instance('Left icon placeholder'),
      // "rightIconPlaceholder": figma.instance('Right icon placeholder'),
      // "description": figma.boolean('Description'),
      // "descriptionText": figma.string('Description text'),
      // "prefix": figma.boolean('Prefix'),
      // "suffix": figma.boolean('Suffix')
    },
    example: (props) => (
      <TextField
        size={props.size}
        description={props.description}
        iconLeft={props.iconLeft}
        iconRight={props.iconRight}
        isDisabled={props.isDisabled}
      />
    ),
  },
)
