import React from "react"
import ToggleButton from "./ToggleButton"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  ToggleButton,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=14991%3A13794",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("Size", {
        Small: "small",
        Medium: "medium",
      }),
      isIconButton: figma.boolean("Icon button?"),
      isSelected: figma.boolean("Selected"),
      defaultSelected: figma.boolean("Selected"),
      isDisabled: figma.enum("State", {
        Disabled: true,
      }),
      hidden: figma.enum("State", {
        Disabled: true,
      }),
      // No matching props could be found for these Figma properties:
      // "iconRight": figma.boolean('Icon right'),
      // "iconLeft": figma.boolean('Icon left'),
      // "iconLeftPlaceholder": figma.instance('Icon left placeholder'),
      // "iconRightPlaceholder": figma.instance('Icon right placeholder'),
      // "iconButtonPlaceholder": figma.instance('Icon button placeholder')
    },
    example: (props) => (
      <ToggleButton
        size={props.size}
        isIconButton={props.isIconButton}
        isSelected={props.isSelected}
        defaultSelected={props.defaultSelected}
        isDisabled={props.isDisabled}
        hidden={props.hidden}
      />
    ),
  },
)
