import AlertDialog from "./AlertDialog"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  AlertDialog,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=6433%3A1885",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      title: figma.string("Title"),
      variant: figma.enum("Type", {
        "Confirmation": "confirmation",
        "Information": "information",
        "Error": "error",
        "Destructive": "destructive",
        "Warning": "warning",
      }),
      // No matching props could be found for these Figma properties:
      // "title": figma.string('Title'),
      // "swap": figma.instance('Swap'),
      // "text": figma.string('Text'),
    },
    example: (props) => <AlertDialog title={props.title} />,
  },
)
