import Callout from "./Callout";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Callout,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=7782%3A3976",
  {
    props: {
      variant: figma.enum("Color", {
        "Light gray": "lightGrey",
        "Light blue": "lightBlue",
        "Light gold": "lightGold",
        Black: "Black",
        Gray: "Grey",
        Blue: "Blue",
      }),
      // No matching props could be found for these Figma properties:
      // "heading": figma.boolean('Heading'),
      // "actions": figma.boolean('Actions'),
      // "stroke": figma.boolean('Stroke'),
      // "primary": figma.boolean('Primary'),
      // "secondary": figma.boolean('Secondary'),
    },
    example: (props) => <Callout variant={props.variant} />,
  }
);
