import React from "react"
import Callout from "./Callout"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Callout,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=7782%3A3976",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "heading": figma.boolean('Heading'),
      // "actions": figma.boolean('Actions'),
      // "stroke": figma.boolean('Stroke'),
      // "primary": figma.boolean('Primary'),
      // "secondary": figma.boolean('Secondary'),
      // "color": figma.enum('Color', {
      //   "Light gray": "light-gray",
      //   "Light blue": "light-blue",
      //   "Light gold": "light-gold",
      //   "Black": "black",
      //   "Gray": "gray",
      //   "Blue": "blue"
      // })
    },
    example: (props) => <Callout />,
  },
)
