import React from "react"
import Tooltip from "./Tooltip"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Tooltip,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=3572%3A1939",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "direction": figma.enum('Direction', {
      //   "← Left": "--left",
      //   "→ Right": "--right",
      //   "↑ Up": "--up",
      //   "↓ Down": "--down"
      // })
    },
    example: (props) => <Tooltip />,
  },
)
