import ProgressCircle from "./ProgressCircle";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  ProgressCircle,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=16696%3A837",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("Track Size", {
        Small: "small",
        Medium: "medium",
        Large: "large",
      }),
      valueLabel: figma.string("Label"),
      value: figma.string("Value"),
      isIndeterminate: figma.enum("Style", {
        Indeterminate: true,
      }),
      // No matching props could be found for these Figma properties:
      // "description": figma.boolean('Description'),
      // "color": figma.enum('Color', {
      //   "Default": "default",
      //   "Over Background": "over-background"
      // })
    },
    example: (props) => (
      <ProgressCircle
        size={props.size}
        valueLabel={props.valueLabel}
        value={Number(props.value) || 0}
        isIndeterminate={props.isIndeterminate}
      />
    ),
  }
);
