import Footer from "./Footer";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Footer,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=3982%3A10968",
  {
    imports: ["import { Footer } from '@bcgov/design-system-react-components'"],
    props: {
      hideAcknowledgement: figma.boolean("Land acknowledgement", {
        false: true,
        true: false,
      }),
      hideLogoAndLinks: figma.boolean("Content", {
        false: true,
        true: false,
      }),
      hideCopyright: figma.boolean("Copyright", {
        false: true,
        true: false,
      }),
      acknowledgement: figma.slot("Territorial acknowledgement content"),
      children: figma.slot("Slot"),
      // No matching props could be found for these Figma properties:
      // "content": figma.boolean('Content'),
      // "type": figma.enum('Type', {
      //   "Default": "default"
      // })
    },
    example: (props) => (
      <Footer
        hideLogoAndLinks={props.hideLogoAndLinks}
        hideCopyright={props.hideCopyright}
        hideAcknowledgement={props.hideAcknowledgement}
        acknowledgement={props.acknowledgement}
      >
        {props.children}
      </Footer>
    ),
  }
);
