import DatePicker from "./DatePicker";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  DatePicker,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=15865%3A4285",
  {
    imports: [
      "import { DatePicker } from '@bcgov/design-system-react-components'",
    ],
    props: {
      size: figma.enum("Size", {
        Small: "small",
        Medium: "medium",
      }),
      hideTimeZone: figma.boolean("Timezone", {
        false: true,
        true: false,
      }),
      isRequired: figma.nestedProps("Title", figma.boolean("Required")),
      isDisabled: figma.enum("State", {
        Disabled: true,
      }),
      isReadOnly: figma.enum("State", {
        "Read only": true,
      }),
      isCalendarDisabled: figma.boolean("Show calendar", {
        false: true,
        true: false,
      }),
      label: figma.nestedProps("Title", figma.string("Label text")),
      description: figma.textContent("Description"),
      // No matching props could be found for these Figma properties:
      // "showLabel": figma.boolean('Show label'),
      // "time": figma.boolean('Time'),
      // "description": figma.boolean('Description')
    },
    example: (props) => (
      <DatePicker
        size={props.size}
        hideTimeZone={props.hideTimeZone}
        isRequired={props.isRequired}
        isDisabled={props.isDisabled}
        isReadOnly={props.isReadOnly}
        label={props.label}
      />
    ),
  }
);
