import React from "react"
import DatePicker from "./DatePicker"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  DatePicker,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=15865%3A4285",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("Size", {
        Small: "small",
        Medium: "medium",
      }),
      hideTimeZone: figma.boolean("Timezone"),
      isDisabled: figma.enum("State", {
        Disabled: true,
      }),
      isReadOnly: figma.enum("State", {
        "Read only": true,
      }),
      hidden: figma.enum("State", {
        Disabled: true,
      }),
      // No matching props could be found for these Figma properties:
      // "showLabel": figma.boolean('Show label'),
      // "showCalendar": figma.boolean('Show calendar'),
      // "time": figma.boolean('Time'),
      // "timezone": figma.boolean('Timezone'),
      // "description": figma.boolean('Description')
    },
    example: (props) => (
      <DatePicker
        size={props.size}
        hideTimeZone={props.hideTimeZone}
        isDisabled={props.isDisabled}
        isReadOnly={props.isReadOnly}
        hidden={props.hidden}
      />
    ),
  },
)
