// This file is used to map component props to Figma properties via Code Connect
import Button from "./Button";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Button,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=14242%3A1245",
  {
    imports: ["import { Button } from '@bcgov/design-system-react-components'"],
    props: {
      size: figma.enum("Size", {
        Xsmall: "xsmall",
        Small: "small",
        Medium: "medium",
        Large: "large",
      }),
      variant: figma.enum("Hierarchy", {
        Primary: "primary",
        Secondary: "secondary",
        Tertiary: "tertiary",
        Link: "link",
      }),
      danger: figma.boolean("Danger"),
      isDisabled: figma.enum("State", {
        Disabled: true,
      }),
      children: figma.textContent("Button Label"),
      // No matching props could be found for these Figma properties:
      // "showLeftIcon": figma.boolean('Show left icon'),
      // "showRightIcon": figma.boolean('Show right icon'),
      // "leftSideIcon": figma.instance('Left side icon '),
      // "rightSideIcon": figma.instance('Right side icon'),
    },
    example: (props) => (
      <Button
        size={props.size}
        variant={props.variant}
        danger={props.danger}
        isDisabled={props.isDisabled}
      >
        {props.children}
      </Button>
    ),
  }
);
