import Checkbox from "./Checkbox";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Checkbox,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=6009%3A878",
  {
    imports: [
      "import { Checkbox } from '@bcgov/design-system-react-components'",
    ],
    props: {
      // These props were automatically mapped based on your linked code:
      isSelected: figma.enum("State", {
        Inactive: false,
        Active: true,
      }),
      isIndeterminate: figma.enum("Selection", {
        Indeterminate: true,
      }),
      isDisabled: figma.enum("State", {
        Disabled: true,
      }),
      isRequired: figma.nestedProps("Label", figma.boolean("Required")),
      children: figma.nestedProps("Label", figma.string("Label text")),
      // No matching props could be found for these Figma properties:
      // "label": figma.boolean('Label')
    },
    example: (props) => (
      <Checkbox
        isIndeterminate={props.isIndeterminate}
        isSelected={props.isSelected}
        isDisabled={props.isDisabled}
        isRequired={props.isRequired}
      >
        {props.children}
      </Checkbox>
    ),
  }
);
