import Header from "./Header";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Header,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=4017%3A17444",
  {
    imports: [
      "import { Header } from '@bcgov/design-system-react-components';",
    ],
    props: {
      // These props were automatically mapped based on your linked code:
      logoImage: figma.instance("Logo"),
      children: figma.children("Header content"),
      // No matching props could be found for these Figma properties:
      // "showTitle": figma.boolean('Show title'),
      // "hasSubheader": figma.boolean('Has subheader')
    },
    example: (props) => (
      <Header logoImage={props.logoImage}>{props.children}</Header>
    ),
  }
);
