import React from "react"
import Header from "./Header"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Header,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=4017%3A17444",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "logo": figma.instance('Logo'),
      // "showTitle": figma.boolean('Show title'),
      // "hasSubheader": figma.boolean('Has subheader')
    },
    example: (props) => <Header />,
  },
)
