name: Publish @bcgov/design-system-react-components to npm and GitHub Packages

on:
  pull_request:
    paths:
      - packages/react-components/**
    branches: [main]
    types: [closed]
  release:
    types: [published]

jobs:
  build:
    if: ${{ (github.event.pull_request.merged == true && github.repository == 'bcgov/design-system') || (github.event_name == 'release' && contains(github.event.release.tag_name, 'bcgov/design-system-react-components')) }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      node-version: ${{ steps.nvmrc.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Read .nvmrc
        id: nvmrc
        run: echo "version=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        working-directory: ./packages/react-components

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ steps.nvmrc.outputs.version }}

      - name: Install dependencies
        run: npm ci
        working-directory: ./packages/react-components

      - name: Install jq
        if: ${{ github.event.pull_request.merged == true }}
        run: sudo apt-get install -y jq

      # Append PR number to version number in package.json
      - name: Update version in package.json
        if: ${{ github.event.pull_request.merged == true }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          CURRENT_VERSION=$(jq -r '.version' package.json)
          NEW_VERSION="${CURRENT_VERSION}-pr${PR_NUMBER}"
          jq --arg new_version "$NEW_VERSION" '.version = $new_version' package.json > tmp.json && mv tmp.json package.json
        shell: bash
        working-directory: ./packages/react-components

      - name: Build components for publishing
        run: npm run build
        working-directory: ./packages/react-components

      - name: Publish Figma Code Connect files
        if: ${{ github.event_name == 'release' && contains(github.event.release.tag_name, 'bcgov/design-system-react-components') }}
        run: npx figma connect publish --token "$FIGMA_ACCESS_TOKEN"
        working-directory: ./packages/react-components
        env:
          FIGMA_ACCESS_TOKEN: ${{ secrets.FIGMA_ACCESS_TOKEN }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-components-build
          path: |
            packages/react-components
            !packages/react-components/node_modules

  publish-npm-next:
    needs: build
    if: ${{ github.event.pull_request.merged == true && github.repository == 'bcgov/design-system' }}
    permissions:
      contents: read
      id-token: write # Required for OIDC
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: react-components-build

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ needs.build.outputs.node-version }}
          registry-url: "https://registry.npmjs.org/"

      - name: Publish to npm @next
        run: npm publish --tag next --provenance
        working-directory: ./packages/react-components

  publish-github-packages-next:
    needs: build
    if: ${{ github.event.pull_request.merged == true && github.repository == 'bcgov/design-system' }}
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: react-components-build

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ needs.build.outputs.node-version }}
          registry-url: "https://npm.pkg.github.com/"
          scope: "@bcgov"

      - name: Publish to GitHub Packages @next
        run: npm publish --tag next --registry=https://npm.pkg.github.com/
        working-directory: ./packages/react-components
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-npm-latest:
    needs: build
    if: ${{ github.event_name == 'release' && contains(github.event.release.tag_name, 'bcgov/design-system-react-components') }}
    permissions:
      contents: read
      id-token: write # Required for OIDC
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: react-components-build

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ needs.build.outputs.node-version }}
          registry-url: "https://registry.npmjs.org/"

      - name: Publish to npm @latest
        run: npm publish --tag latest --provenance
        working-directory: ./packages/react-components

  publish-github-packages-latest:
    needs: build
    if: ${{ github.event_name == 'release' && contains(github.event.release.tag_name, 'bcgov/design-system-react-components') }}
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: react-components-build

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ needs.build.outputs.node-version }}
          registry-url: "https://npm.pkg.github.com/"
          scope: "@bcgov"

      - name: Publish to GitHub Packages
        run: npm publish --registry=https://npm.pkg.github.com/
        working-directory: ./packages/react-components
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
