name: Publish @bcgov/design-system-react-components to npm

on:
  pull_request:
    paths:
      - packages/react-components/**
    branches: [main]
    types: [closed]
  release:
    types: [published]

permissions:
  id-token: write # Required for OIDC
  contents: read
  packages: write

jobs:
  publish-npm-next:
    # Publish a `next` version to npm on PR merge to `main`
    if: ${{ github.event.pull_request.merged == true && github.repository == 'bcgov/design-system' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Read .nvmrc
        run: echo "GITHUB_NVMRC_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV
        working-directory: ./packages/react-components

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.GITHUB_NVMRC_VERSION }}
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        run: npm install
        working-directory: ./packages/react-components

      - name: Install jq
        run: sudo apt-get install -y jq

      # Append PR number to version number in package.json
      - name: Update version in package.json
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          CURRENT_VERSION=$(jq -r '.version' package.json)
          NEW_VERSION="${CURRENT_VERSION}-pr${PR_NUMBER}"
          jq --arg new_version "$NEW_VERSION" '.version = $new_version' package.json > tmp.json && mv tmp.json package.json
        shell: bash
        working-directory: ./packages/react-components

      - name: Build components for publishing
        run: npm run build
        working-directory: ./packages/react-components

      - name: Publish to npm @next
        run: npm publish --tag next --provenance
        working-directory: ./packages/react-components

  publish-github-packages-next:
    # Publish a `next` version to GitHub Packages on PR merge to `main`
    if: ${{ github.event.pull_request.merged == true && github.repository == 'bcgov/design-system' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Read .nvmrc
        run: echo "GITHUB_NVMRC_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV
        working-directory: ./packages/react-components

      - name: Set up Node.js for GitHub Packages
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.GITHUB_NVMRC_VERSION }}
          registry-url: "https://npm.pkg.github.com/"
          scope: "@bcgov"

      - name: Install dependencies
        run: npm install
        working-directory: ./packages/react-components

      - name: Install jq
        run: sudo apt-get install -y jq

      # Append PR number to version number in package.json
      - name: Update version in package.json
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          CURRENT_VERSION=$(jq -r '.version' package.json)
          NEW_VERSION="${CURRENT_VERSION}-pr${PR_NUMBER}"
          jq --arg new_version "$NEW_VERSION" '.version = $new_version' package.json > tmp.json && mv tmp.json package.json
        shell: bash
        working-directory: ./packages/react-components

      - name: Build components for publishing
        run: npm run build
        working-directory: ./packages/react-components

      - name: Publish to GitHub Packages @next
        run: npm publish --tag next --registry=https://npm.pkg.github.com/
        working-directory: ./packages/react-components
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-npm-latest:
    # Publish a `latest` version to npm when a release is published that targets `@bcgov/design-system-react-components`
    if: ${{ github.event_name == 'release' && contains(github.event.release.tag_name, 'bcgov/design-system-react-components') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Read .nvmrc
        run: echo "GITHUB_NVMRC_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV
        working-directory: ./packages/react-components

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.GITHUB_NVMRC_VERSION }}
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        run: npm install
        working-directory: ./packages/react-components

      - name: Build components for publishing
        run: npm run build
        working-directory: ./packages/react-components

      - name: Publish to npm @latest
        run: npm publish --tag latest --provenance
        working-directory: ./packages/react-components

  publish-github-packages-latest:
    # Publish a `latest` version to GitHub Packages when a release is published that targets `@bcgov/design-system-react-components`
    if: ${{ github.event_name == 'release' && contains(github.event.release.tag_name, 'bcgov/design-system-react-components') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Read .nvmrc
        run: echo "GITHUB_NVMRC_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV
        working-directory: ./packages/react-components

      - name: Set up Node.js for GitHub Packages
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.GITHUB_NVMRC_VERSION }}
          registry-url: "https://npm.pkg.github.com/"
          scope: "@bcgov"

      - name: Install dependencies
        run: npm install
        working-directory: ./packages/react-components

      - name: Build components for publishing
        run: npm run build
        working-directory: ./packages/react-components

      - name: Publish to GitHub Packages @latest
        run: npm publish --tag latest --registry=https://npm.pkg.github.com/
        working-directory: ./packages/react-components
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
