name: Test design tokens build script

on:
  pull_request:
    paths:
      - packages/design-tokens/**
  workflow_dispatch:

# Cancel any currently running builds to save GitHub Actions hours.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read .nvmrc
        run: echo "GITHUB_NVMRC_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV
        working-directory: ./packages/design-tokens

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.GITHUB_NVMRC_VERSION }}

      - name: Install dependencies
        run: npm install
        working-directory: ./packages/design-tokens

      - name: Run test suite with npm script
        run: npm run test
        working-directory: ./packages/design-tokens
