import React from "react"
import RadioGroup from "./RadioGroup"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  RadioGroup,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=6009%3A2784",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      orientation: figma.enum("Layout", {
        Vertical: "vertical",
        Horizontal: "horizontal",
      }),
      // No matching props could be found for these Figma properties:
      // "errorText": figma.boolean('Error text'),
      // "description": figma.boolean('Description'),
      // "label": figma.boolean('Label'),
      // "count": figma.enum('Count', {
      //   "2": "2",
      //   "3": "3",
      //   "4": "4",
      //   "5": "5",
      //   "6": "6",
      //   "7": "7",
      //   "8": "8"
      // })
    },
    example: (props) => <RadioGroup orientation={props.orientation} />,
  },
)
