import RadioGroup from "./RadioGroup";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  RadioGroup,
  "https://www.figma.com/design/6BAmnRmL9FXxY2bkkSYiQj/B.C.-Design-System?node-id=6009%3A2784",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      orientation: figma.enum("Orientation", {
        Vertical: "vertical",
        Horizontal: "horizontal",
      }),
      label: figma.textContent("Label"),
      description: figma.textContent("Description"),
      errorMessage: figma.textContent("Error message"),
      children: figma.slot("Slots"),
    },
    example: (props) => (
      <RadioGroup
        orientation={props.orientation}
        label={props.label}
        description={props.description}
        errorMessage={props.errorMessage}
      >
        {props.children}
      </RadioGroup>
    ),
  }
);
